# Generated by Django 5.2.6 on 2025-10-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='conEmail',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='conLName',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sub',
            new_name='conMessage',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='namefamily',
            new_name='conName',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='number',
            new_name='conPhone',
        ),
    ]
