# Generated by Django 5.2.6 on 2025-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_rename_email_message_conemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conLName',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='conMessage',
            field=models.CharField(max_length=255),
        ),
    ]
