# Generated by Django 5.2.6 on 2025-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_alter_message_conlname_alter_message_conmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
