# Generated by Django 5.2.6 on 2025-10-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='change_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('number', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
