# Generated by Django 5.2.6 on 2025-10-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_icon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_icon',
            name='number',
            field=models.IntegerField(),
        ),
    ]
